[project]
name = "extension-demography"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiosql>=13.4",
    "duckdb>=1.3.0",
    "fastapi>=0.115.12",
    "glootil>=0.2.5",
    "uvicorn>=0.34.2",
]
